// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.36.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<Uint8List> overlayImageWithWatermark(
        {required ImageOverlayInput input, dynamic hint}) =>
    RustLib.instance.api
        .crateApiVipsApiOverlayImageWithWatermark(input: input, hint: hint);

class ImageOverlayInput {
  final Uint8List inputImage;
  final Uint8List overlayImage;
  final int overlayWidth;
  final int overlayHeight;
  final int x;
  final int y;

  const ImageOverlayInput({
    required this.inputImage,
    required this.overlayImage,
    required this.overlayWidth,
    required this.overlayHeight,
    required this.x,
    required this.y,
  });

  @override
  int get hashCode =>
      inputImage.hashCode ^
      overlayImage.hashCode ^
      overlayWidth.hashCode ^
      overlayHeight.hashCode ^
      x.hashCode ^
      y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageOverlayInput &&
          runtimeType == other.runtimeType &&
          inputImage == other.inputImage &&
          overlayImage == other.overlayImage &&
          overlayWidth == other.overlayWidth &&
          overlayHeight == other.overlayHeight &&
          x == other.x &&
          y == other.y;
}
